2023-07-16 02:51:30,457 - Test - ERROR - Exception occurred in test: division by zero
The error is in lines 9 to 9 of file G:\Source\AutoUpload\src\test.py, which has the code:'print(1 / 0)' in function test. The local variable is: None.
2023-07-16 03:03:27,881 - Abc - ERROR - Exception occurred in test: Test.test() takes 0 positional arguments but 1 was given
The error is in lines 81 to 81 of file G:\Source\AutoUpload\src\Logger.py, which has the code:'return func(*args, **kwargs)' in function wrapper. The local variable is: None.
2023-07-16 03:04:38,441 - Abc - ERROR - Exception occurred in test: Test.test() takes 0 positional arguments but 1 was given
The error is in lines 81 to 81 of file G:\Source\AutoUpload\src\Logger.py, which has the code:'return func(*args, **kwargs)' in function wrapper. The local variable is: None.
2023-07-16 03:05:13,800 - Abc - ERROR - Exception occurred in test: Test.test() takes 0 positional arguments but 1 was given
The error is in lines 81 to 81 of file G:\Source\AutoUpload\src\Logger.py, which has the code:'return func(*args, **kwargs)' in function wrapper. The local variable is: None.
2023-07-16 03:16:47,360 - Test - ERROR - Exception occurred in test: Test.test() takes 0 positional arguments but 1 was given
The error is in lines 82 to 82 of file G:\Source\AutoUpload\src\Logger.py, which has the code:'return func(*args, **kwargs)' in function wrapper. The local variable is: None.
2023-07-16 03:18:14,926 - Test - ERROR - Exception occurred in test: division by zero
The error is in lines 23 to 23 of file G:\Source\AutoUpload\src\test.py, which has the code:'print(1 / 0)' in function test. The local variable is: None.
